title: Joe Gannon
description: My Personal Stack Problems
author: Joe Gannon
github: https://github.com/joegannon
about: Software Developer
disqus_shortname: joegannon
google_analytics: UA-145843671-1

enableTags: false

social:    
    - icon: fa-twitter
      link: "https://twitter.com/_joegannon"    
    - icon: fa-github
      link: "https://github.com/JoeGannon"
      
share:
  twitter_username: _joegannon
  #fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/   
    - text: XML Feed
      url: /feed.xml

url: "https://joegannon.dev"
baseurl: ""
paginate: 100
per_page: 100
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
